### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by thewh1teagle** [Nriver/anki-web-server-docker#1]
I tried to run it as described in the readme but I got errors.

```
[user@arch temp]$ git clone https://github.com/Nriver/anki-web-server-docker.git
[user@arch temp]$ cd anki-web-server-docker
[user@arch anki-web-server-docker]$ ./init.sh
```
```bash
[user@arch anki-web-server-docker]$ docker-compose up
WARNING: The PWD variable is not set. Defaulting to a blank string.
Starting anki-web-server-docker_ankisyncserver_1 ... done
Starting anki-web-server-docker_ankiwebserver_1  ... done
Attaching to anki-web-server-docker_ankisyncserver_1, anki-web-server-docker_ankiwebserver_1
ankisyncserver_1  | [2021-03-29 23:46:13,256]:INFO:ankisyncd:ankisyncd [unknown version] (https://github.com/ankicommunity/anki-sync-server.git)
ankisyncserver_1  | Traceback (most recent call last):
ankisyncserver_1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
ankisyncserver_1  |     return _run_code(code, main_globals, None,
ankisyncserver_1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
ankisyncserver_1  |     exec(code, run_globals)
ankisyncserver_1  |   File "/app/ankisyncd/__main__.py", line 11, in <module>
ankisyncserver_1  |     ankisyncd.sync_app.main()
ankisyncserver_1  |   File "/app/ankisyncd/sync_app.py", line 617, in main
ankisyncserver_1  |     config = ankisyncd.config.load()
ankisyncserver_1  |   File "/app/ankisyncd/config.py", line 42, in load
ankisyncserver_1  |     raise Exception("No config found, looked for {}".format(", ".join(choices)))
ankisyncserver_1  | Exception: No config found, looked for /etc/ankisyncd/ankisyncd.conf, /root/.config/ankisyncd/ankisyncd.conf, /app/ankisyncd.conf
ankiwebserver_1   | Traceback (most recent call last):
ankiwebserver_1   |   File "app.py", line 14, in <module>
ankiwebserver_1   |     from flaskbp import create_app
ankiwebserver_1   |   File "/app/flaskbp/__init__.py", line 9, in <module>
ankiwebserver_1   |     from flaskbp.module.decks import bp_decks
ankiwebserver_1   |   File "/app/flaskbp/module/decks/__init__.py", line 10, in <module>
ankiwebserver_1   |     from . import views
ankiwebserver_1   |   File "/app/flaskbp/module/decks/views.py", line 12, in <module>
ankiwebserver_1   |     from flaskbp.utils.db_util import get_auth_db, get_collection
ankiwebserver_1   |   File "/app/flaskbp/utils/db_util.py", line 7, in <module>
ankiwebserver_1   |     from settings import data_root, auth_db_path
ankiwebserver_1   |   File "/app/settings.py", line 12, in <module>
ankiwebserver_1   |     config = conf['web_app']
ankiwebserver_1   |   File "/usr/local/lib/python3.8/configparser.py", line 960, in __getitem__
ankiwebserver_1   |     raise KeyError(key)
ankiwebserver_1   | KeyError: 'web_app'
anki-web-server-docker_ankisyncserver_1 exited with code 1
anki-web-server-docker_ankiwebserver_1 exited with code 1
[user@arch anki-web-server-docker]$
```

Additional info

```
docker-compose version 1.28.6, build unknown
Docker version 20.10.5, build 55c4c88966


                   -`                    user@arch
                  .o+`                   ----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: 20AN00CCIV ThinkPad T440p
               `+oooooo:                 Kernel: 5.11.10-arch1-1
               -+oooooo+:                Uptime: 1 hour, 6 mins
             `/:-:++oooo+:               Packages: 634 (pacman)
            `/++++/+++++++:              Shell: bash 5.1.4
           `/++++++++++++++:             Resolution: 1920x1080
          `/+++ooooooooooooo/`           DE: Plasma 5.21.3
         ./ooosssso++osssssso+`          WM: KWin
        .oossssso-````/ossssss+`         WM Theme: Breeze
       -osssssso.      :ssssssso.        Theme: Breeze Dark [Plasma], Adwaita [GTK3]
      :osssssss/        osssso+++.       Icons: breeze-dark [Plasma], Adwaita [GTK3]
     /ossssssss/        +ssssooo/-       Terminal: alacritty
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-4710MQ (8) @ 3.500GHz
  `+sso+:-`                 `.-/+oso:    GPU: Intel 4th Gen Core Processor
 `++:.                           `-/+/   GPU: NVIDIA GeForce GT 730M
 .`                                 `/   Memory: 2087MiB / 11859MiB

```

**Comment by Nriver** [comment]
It seems docker could not get the ${PWD} variable on some linux distribution. I have updated the `docker-compose.yml` to use relative path. Please update and tell me if it works for you.

**Comment by thewh1teagle** [comment]
It worked, thank you!

**Comment by Nriver** [comment]
Problem solved.
